### ISSUE TITLE
Exception when both events have no schedules

### ISSUE THREAD

**Issue by NYPD** [NYPD/soil-and-pimp-live-web#74]
https://github.com/NYPD/soil-and-pimp-live-web/blob/67b1bf1fd4fae803bf6450f5192c15c9e9211e42/src/live/soilandpimp/domain/Event.java#L277

```
[2021-06-05 13:29:57.412] [ERROR] (ControllerAdvisor.java:handleGeneralException():81) - Something messed up
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:657)
        at java.util.ArrayList.get(ArrayList.java:433)
        at org.hibernate.collection.internal.PersistentBag.get(PersistentBag.java:450)
        at live.soilandpimp.domain.Event$EventFirstScheduleComparatorDesc.compare(Event.java:277)
        at live.soilandpimp.domain.Event$EventFirstScheduleComparatorDesc.compare(Event.java:261)
        at java.util.TimSort.binarySort(TimSort.java:296)
        at java.util.TimSort.sort(TimSort.java:239)
        at java.util.Arrays.sort(Arrays.java:1512)
        at java.util.ArrayList.sort(ArrayList.java:1462)
        at java.util.Collections.sort(Collections.java:175)
        at live.soilandpimp.service.DefaultMainService.getPastEvents(DefaultMainService.java:72)
        at sun.reflect.GeneratedMethodAccessor423.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:206)
        at com.sun.proxy.$Proxy70.getPastEvents(Unknown Source)
        at live.soilandpimp.controller.MainController.getPastEventsPage(MainController.java:35)
```

**Comment by NYPD** [comment]
Fixed in #81 

Wow 3 year old bug, wonder how it temp fixed it back then
